name: routesim
channels:
  - defaults
dependencies:
  - ipykernel=6.29.5
  - pip=26.0.1
  - python=3.12.11
  - pip:
      - dask==2026.3.0
      - multiprocess==0.70.19
      - networkx==3.6.1
      - numpy==1.26.4
      - pandas==2.3.3
      - pyarrow==24.0.0
      - pydantic==2.13.3
      - pymongo==4.17.0
      - rdchiral==1.1.0
      - rdkit==2023.9.6
      - reaction-utils==1.9.3
      - regex==2026.4.4
      - requests==2.33.1
      - rxn-chem-utils==1.6.0
      - rxn-utils==2.0.0
      - rxnmapper==0.4.3
      - scipy==1.17.1
      - torch==2.2.2
      - tqdm==4.67.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==1.26.20