name: rev_plot
channels:
  - defaults
dependencies:
  - ipykernel=6.29.5
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.6
  - numpy=1.26.4
  - pandas=2.3.1
  - pip=26.0.1
  - python=3.12.11
  - scipy=1.16.0
  - seaborn=0.13.2
