name: syngps
channels:
  - conda-forge
  - defaults
dependencies:
  - graphblas=9.4.5
  - pydantic=2.11.4
  - graphblas-algorithms=2023.10.0
  - ipython=9.1.0
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyterlab=4.3.4
  - networkx=3.4.2
  - numpy=2.2.5
  - pandas=2.2.3
  - pip=25.0
  - python=3.12.2
  - requests=2.32.3
  - scipy=1.15.2
  - rdkit=2025.03.2
 